### PR TITLE
added: product (Bio Link)

### PR DESCRIPTION
**Pull request by AnikAdhikari7**
|[Bio Link](https://bio.link/)|Link in bio - the clickable URL that you can add to your profile section|Social Media Links Manager|

# Issue Number : 
.
.
.
# Modified File Path : 
.
.
.
# Description : 
.
.
.
# Mentions : 
@ShreyamMaity

### CODE REVIEW

**Comment by AnikAdhikari7** [comment]
added: product (Bio Link) #83
|[Bio Link](https://bio.link/)|Link in bio - the clickable URL that you can add to your profile section|Social Media Links Manager|

**Comment by ShreyamMaity** [comment]
if they're not having any benefits for students then don't add them

**Comment by AnikAdhikari7** [comment]
> if they're not having any benefits for students then don't add them

it's very helpful to students. in bio.link we can add our different social media profile links like Github, Linkedin in on place.
example: https://bio.link/anikadhikari

**Comment by ShreyamMaity** [comment]
> > if they're not having any benefits for students then don't add them
> 
> it's very helpful to students. in bio.link we can add our different social media profile links like Github, Linkedin in on place. example: https://bio.link/anikadhikari

ok then, approving

**Comment by AnikAdhikari7** [comment]
thank you bhaiya!😊

**Pull request merged**
