### PR TITLE
Updated database.md

### PR DESCRIPTION
**Pull request by sayandeep-adhikary**
Changed the link of Rhino3D educational license link

# Issue Number : #3
.
.
.
# Modified File Path : /database/database.md
.
.
.
# Description : Updated the Rhino3D educational license link
.
.
.
# Mentions : 
@ShreyamMaity

### CODE REVIEW

**Comment by sayandeep-adhikary** [comment]
Updated the link. please check again

**Comment by ShreyamMaity** [comment]
line no `27,29,49` , remove those . or take a fresh pull from the main. it got updated

**Comment by sayandeep-adhikary** [comment]
@ShreyamMaity I don't know how those lines got added in my commit but  I can not see them in the main branch. If it creates any problem, I request you to do the necessary deletion. Sorry for the mistake.

**Comment by ShreyamMaity** [comment]
> @ShreyamMaity I don't know how those lines got added in my commit but I can not see them in the main branch. If it creates any problem, I request you to do the necessary deletion. Sorry for the mistake.

ok cool

**Pull request merged**
