### PR TITLE
Removed Storyscript

### PR DESCRIPTION
**Pull request by amrit03b**
# Issue Number : 
.
.
.
# Modified File Path : 
.
.
.
# Description : Removed Storyscript(line 148) as no such website exists as of now.
.
.
.
# Mentions : 
@ShreyamMaity

### CODE REVIEW

**Review by ShreyamMaity — APPROVED** [review]
That's awesome work. I've searched a bit. Seems like it's been rebranded to story.ai. Do check if it's the same and if it still provides a licence for students.

**Comment by amrit03b** [comment]
Unable to find story.ai website. Maybe it also doesn't exists.

**Comment by ShreyamMaity** [comment]
seems like their website is not working anymore.
https://www.linkedin.com/company/storyai/
here is their linkedin page

**Comment by amrit03b** [comment]
Thanks for the update. Since it's not working anymore, I am not adding it.

**Comment by ShreyamMaity** [comment]
Yea sure.

**Pull request merged**
